include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

  exclude:
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/injection.config.dart"
    - "lib/injection.config.dart"

  errors:
    invalid_use_of_protected_member: warning
    unnecessary_statements: error
    prefer_const_constructors: error
    prefer_const_declarations: error
    prefer_const_constructors_in_immutables: error
    prefer_const_literals_to_create_immutables: error
    prefer_final_fields: error
    prefer_final_locals: error
    avoid_unused_constructor_parameters: error
    always_specify_types: error
    curly_braces_in_flow_control_structures: error
    library_prefixes: error
    prefer_conditional_assignment: error
    prefer_if_null_operators: error
    library_names: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_spread_collections: error
    recursive_getters: error
    use_rethrow_when_possible: error
    prefer_equal_for_default_values: error
    prefer_collection_literals: error
    prefer_adjacent_string_concatenation: error
    unnecessary_new: error
    missing_return: error
    avoid_returning_null_for_void: error
    import_of_legacy_library_into_null_safe: error
    sized_box_for_whitespace: error
    prefer_typing_uninitialized_variables: error
    file_names: error
    avoid_init_to_null: error
    always_declare_return_types: warning
    avoid_print: warning
    prefer_contains: warning
    prefer_single_quotes: warning
    cancel_subscriptions: warning
    avoid_unnecessary_containers: warning
    always_put_required_named_parameters_first: warning
    unused_local_variable: warning
    dead_code: warning
    unnecessary_import: warning
    unused_import: warning
    duplicate_import: warning
    avoid_relative_lib_imports: warning
    always_use_package_imports: warning
    unused_catch_stack: warning
    unnecessary_non_null_assertion: warning
    unnecessary_null_comparison: warning
    unnecessary_string_interpolations: warning
    unnecessary_this: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unused_field: warning
    annotate_overrides: warning
    override_on_non_overriding_member: warning
    overridden_fields: warning
    must_call_super: warning
    non_constant_identifier_names: warning
    empty_catches: warning
    constant_identifier_names: info
    ### To set to ERROR
    sized_box_shrink_expand: info
    use_decorated_box: info
    avoid_final_parameters: info
    prefer_initializing_formals: info
    unnecessary_late: info
    no_leading_underscores_for_local_identifiers: info

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list

  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    source-lines-of-code: 250
    number-of-parameters: 6
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - no-empty-block:
        severity: warning
    - no-equal-then-else
    - avoid-unused-parameters
    - no-object-declaration
    # - member-ordering TO SETUP LATER
    - prefer-first:
        severity: warning
    - prefer-last:
        severity: warning
    - prefer-trailing-comma:
        break-on: 3

linter:
  rules:
    # Enabled
    use_rethrow_when_possible: true
    recursive_getters: true
    prefer_spread_collections: true
    always_declare_return_types: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    library_prefixes: true
    prefer_if_null_operators: true
    library_names: true
    prefer_conditional_assignment: true
    prefer_contains: true
    annotate_overrides: true
    always_use_package_imports: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    avoid_unnecessary_containers: true
    valid_regexps: true
    unnecessary_statements: true
    cancel_subscriptions: true
    prefer_single_quotes: true
    avoid_print: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_unused_constructor_parameters: true
    always_put_required_named_parameters_first: true
    curly_braces_in_flow_control_structures: true
    sort_constructors_first: true
    use_build_context_synchronously: true
    # Disabled
    omit_local_variable_types: false
    constant_identifier_names: false
    always_specify_types: false
    lines_longer_than_80_chars: false
    use_key_in_widget_constructors: false
    use_full_hex_values_for_flutter_colors: false
